---
title: "Project 2"
=======:
author: "Amelia Kelly, Greg Ricalde, & Matt Wilchek"
date: "May 1, 2017"
output:
  ioslides_presentation:
    css: bulma.css
    smaller: yes
    transition: slower
    widescreen: yes
runtime: shiny
subtitle: An Exploratory Data Analysis
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# Install necessary packages and include packages.
library(ggplot2) # for graphing
library(lattice) # for graphing
library(car) # for graphing
library(memisc) # for function case
library(HistData) # library containing data
library(grid) # for graphing
library(rsconnect) # for publishing to Shiny apps
library(RCurl) # for importing data from url
library(visreg) # for linear model
library(mice) # to impute values
library(VIM) # to visualize missingness patterns
library(weathermetrics) # to change from Celsius to Fahrenheit
library(miniUI) # for interactive Shiny


# Import Global Temp data
GlobalTemp_csv <- getURL("https://raw.githubusercontent.com/mwilchek/GWU_Project.AnalyzingClimateChange/master/GlobalTemperatures.csv")
GlobalTemp <- read.csv(text = GlobalTemp_csv)
# Delete unwanted columns
GlobalTemp$LandAverageTemperatureUncertainty <- GlobalTemp$LandMaxTemperature <-
GlobalTemp$LandMaxTemperatureUncertainty <- GlobalTemp$LandMinTemperature <-
GlobalTemp$LandMinTemperatureUncertainty <- GlobalTemp$LandAndOceanAverageTemperature <-
GlobalTemp$LandAndOceanAverageTemperatureUncertainty <- GlobalTemp$dt <- GlobalTemp$Day <- GlobalTemp$Month <- NULL
# Change to Fahrenheit
GlobalTemp$LandAverageTemperature <- celsius.to.fahrenheit(GlobalTemp$LandAverageTemperature)
head(GlobalTemp)

# Import City Temp data
CityTemp_csv <- getURL("https://raw.githubusercontent.com/mwilchek/GWU_Project.AnalyzingClimateChange/master/US_City.csv")
CityTemp <- read.csv(text = CityTemp_csv)
# Delete unwanted columns
CityTemp$AverageTemperatureUncertainty <- CityTemp$Country <- NULL
# Change to Fahrenheit
CityTemp$AverageTemperature <- celsius.to.fahrenheit(CityTemp$AverageTemperature)
head(CityTemp)
tail(CityTemp)
```

## Goal (About)

## Research/Background


  
## EDA: Structure and Summary

Examine structure and summary of data

```{r}
# Look at Summary and Structure of both Global and City files.
summary(GlobalTemp)
str(GlobalTemp)

summary(CityTemp)
str(CityTemp)

```

## EDA: Missing Data
Look for missing data and patterns of missing data.
```{r}
# Look for patterns/causes of missing data for both Global and City files.
md.pattern(GlobalTemp)
md.pattern(CityTemp)
global_aggr = aggr(GlobalTemp, numbers=TRUE, sortVars=TRUE, labels=names(GlobalTemp), 
                   cex.axis=.7, gap=3, ylab=c("Proportion of missingness","Missingness Pattern"))
city_aggr = aggr(CityTemp, numbers=TRUE, sortVars=TRUE, labels=names(CityTemp), 
                   cex.axis=.7, gap=3, ylab=c("Proportion of missingness","Missingness Pattern"))

# We are not running models on cities, so we will not impute missing values; eliminate missing values.
GlobalTemp <- GlobalTemp[!(is.na(GlobalTemp$LandAverageTemperature)) | !(is.na(GlobalTemp$LandAverageTemperature)),]
CityTemp <- CityTemp[!(is.na(CityTemp$AverageTemperature)) | !(is.na(CityTemp$AverageTemperature)),]
```

## EDA: Scatterplot

```{r}
# Create aggregate global data
AvgGlobal <- aggregate(GlobalTemp$LandAverageTemperature, 
                       by=list(GlobalTemp$Year), 
                       FUN=mean)

# Plot aggregate global data

qplot(Group.1, x, data=AvgGlobal, main="Global Average Annual Temperature 1753-2013", 
      xlab="Year", ylab="Degrees (Fahrenheit)",
      geom=c("point","smooth"))+ aes(colour = x) + scale_color_gradient(low="blue", high="red")

```


## Maps
```{r}
# Create summary data.
US_City_Simple <- CityTemp
US_City_Simple$dt<- US_City_Simple$Day<- US_City_Simple$Month <- NULL

## Map 2013 Setup for Test Data
US_MapTest <- US_City_Simple[which(US_City_Simple$Year==2013),]
AvgUS_MapTest <- aggregate(US_MapTest$AverageTemperature, 
                     by=list(US_MapTest$Year, US_MapTest$City, US_MapTest$Latitude, US_MapTest$Longitude), 
                     FUN=mean)


# Create Avg Temp by TimeFrame tables.

US_1850_1900 <- US_City_Simple[which(US_City_Simple$Year>=1850 & US_City_Simple$Year<=1900),]
US_1850_1900$Year <- NULL
AvgUS_1850_1900 <- aggregate(US_1850_1900$AverageTemperature, 
                     by=list(US_1850_1900$City, US_1850_1900$Latitude, US_1850_1900$Longitude), 
                     FUN=mean)

US_1901_1950 <- US_City_Simple[which(US_City_Simple$Year>1900 & US_City_Simple$Year<=1950),]
US_1901_1950$Year <- NULL
AvgUS_1901_1950 <- aggregate(US_1901_1950$AverageTemperature, 
                     by=list(US_1901_1950$City, US_1901_1950$Latitude, US_1901_1950$Longitude), 
                     FUN=mean)
  
US_1951_2000 <- US_City_Simple[which(US_City_Simple$Year>1951 & US_City_Simple$Year<=2000),]
US_1951_2000$Year <- NULL
AvgUS_1951_2000 <- aggregate(US_1951_2000$AverageTemperature, 
                     by=list(US_1951_2000$City, US_1951_2000$Latitude, US_1951_2000$Longitude), 
                     FUN=mean)
  
US_2001_2013 <- US_City_Simple[which(US_City_Simple$Year>2000),]
US_2001_2013$Year <- NULL
AvgUS_2001_2013 <- aggregate(US_2001_2013$AverageTemperature, 
                     by=list(US_2001_2013$City, US_2001_2013$Latitude, US_2001_2013$Longitude), 
                     FUN=mean)

```


## Climate Change Model

```{r}
# Overall
qplot(Group.1, x, data=AvgGlobal, main="Global Average Annual Temperature 1753-2013", 
      xlab="Year", ylab="Degrees (Fahrenheit)") + stat_smooth(method = "lm", col = "blue")+ aes(colour = x) + scale_color_gradient(low="blue", high="red")
model_lm <- lm(x ~ Group.1, data=AvgGlobal)

summary(model_lm)

# LM2

GlobalTemp_1850 <- GlobalTemp[which(GlobalTemp$Year >= 1850),]
AvgGlobal_1850 <- aggregate(GlobalTemp_1850$LandAverageTemperature, 
                       by=list(GlobalTemp_1850$Year), 
                       FUN=mean)
qplot(Group.1, x, data=AvgGlobal_1850, main="Global Average Annual Temperature 1850-2013",
      xlab="Year", ylab="Degrees (Fahrenheit)")+ stat_smooth(method = "lm", col = "blue")+ aes(colour = x) + scale_color_gradient(low="blue", high="red")
model_lm2 <- lm(x ~ Group.1, data=AvgGlobal_1850)
summary(model_lm2)

#LM3
GlobalTemp_1900 <- GlobalTemp[which(GlobalTemp$Year >= 1900 & GlobalTemp$Year < 1975),]
AvgGlobal_1900 <- aggregate(GlobalTemp_1900$LandAverageTemperature, 
                            by=list(GlobalTemp_1900$Year), 
                            FUN=mean)
qplot(Group.1, x, data=AvgGlobal_1900, main="Global Average Annual Temperature 1900-1974",
      xlab="Year", ylab="Degrees (Fahrenheit)")+ stat_smooth(method = "lm", col = "blue")+ aes(colour = x) + scale_color_gradient(low="blue", high="red")
model_lm3 <- lm(x ~ Group.1, data=AvgGlobal_1900)
summary(model_lm3)

#LM4
GlobalTemp_1975<- GlobalTemp[which(GlobalTemp$Year >= 1975),]
AvgGlobal_1975 <- aggregate(GlobalTemp_1975$LandAverageTemperature, 
                            by=list(GlobalTemp_1975$Year), 
                            FUN=mean)
qplot(Group.1, x, data=AvgGlobal_1975, main="Global Average Annual Temperature 1975-2013",
      xlab="Year", ylab="Degrees (Fahrenheit)")+ stat_smooth(method = "lm", col = "blue") + aes(colour = x) + scale_color_gradient(low="blue", high="red")
model_lm4 <- lm(x ~ Group.1, data=AvgGlobal_1975)
summary(model_lm4)

```


## Predictions

Predictions based on regression of data from 1975-2013 for future years 2017, 2020, 2050, 2100, 2150 in Fahrenheit:

```{r}
# Run predictions based on last model
futureyears <- data.frame(Group.1=c(2017,2020,2050,2100,2150))
predict(model_lm4, futureyears)

```

Predictions in Celsius:

```{r}
# Convert to Celsius
fahrenheit.to.celsius (predict(model_lm4, futureyears))
```

## Examples


## Interactive Plot

#```{r eruptions}


lmGadget <- function(data, xvar, yvar) {

  ui <- miniPage(
    gadgetTitleBar("Interactive lm"),
    miniContentPanel(
      fillRow(flex = c(NA, 1),
        fillCol(width = "100px",
          selectInput("degree", "Polynomial degree", c(1, 2, 3, 4))
        ),
        plotOutput("plot1",
          height = "100%",
          click = "plot1_click",
          brush = brushOpts(
            id = "plot1_brush"
          )
        )
      )
    ),
    miniButtonBlock(
      actionButton("exclude_toggle", "Toggle points"),
      actionButton("exclude_reset", "Reset")
    )
  )

  server <- function(input, output) {
    # For storing which rows have been excluded
    vals <- reactiveValues(
      keeprows = rep(TRUE, nrow(data))
    )

    output$plot1 <- renderPlot({
      req(input$degree)
      formula <- as.formula(paste0("y ~ poly(x, degree = ", input$degree, ")"))

      # Plot the kept and excluded points as two separate data sets
      keep    <- data[ vals$keeprows, , drop = FALSE]
      exclude <- data[!vals$keeprows, , drop = FALSE]

      ggplot(keep, aes_string(xvar, yvar)) +
        geom_point(size = 3) +
        geom_smooth(method = lm, formula = formula, fullrange = TRUE, color = "gray50") +
        geom_point(data = exclude, fill = NA, color = "black", size = 3, alpha = 0.25) +
        coord_cartesian(xlim = range(data[[xvar]]), ylim = range(data[[yvar]])) +
        theme_bw(base_size = 14)
    })

    # Toggle points that are clicked
    observeEvent(input$plot1_click, {
      res <- nearPoints(data, input$plot1_click, allRows = TRUE)

      vals$keeprows <- xor(vals$keeprows, res$selected_)
    })

    # Toggle points that are brushed, when button is clicked
    observeEvent(input$exclude_toggle, {
      res <- brushedPoints(data, input$plot1_brush, allRows = TRUE)

      vals$keeprows <- xor(vals$keeprows, res$selected_)
    })

    # Reset all points
    observeEvent(input$exclude_reset, {
      vals$keeprows <- rep(TRUE, nrow(data))
    })

    # Handle the Done button being pressed.
    observeEvent(input$done, {
      # Replace x and y in the formula with the values in xvar and yvar
      formula <- as.formula(paste0(yvar, " ~ poly(", xvar, ", degree = ", input$degree, ")"))
      keep_data <- data[vals$keeprows, , drop = FALSE]

      # Return the kept points.
      stopApp(
        list(
          data = keep_data,
          model = lm(formula, keep_data)
        )
      )
    })

  }

  runGadget(ui, server)
}

lmGadget(mtcars, "wt", "mpg")



```

